runs:
  using: "composite"
  steps:
    - name: Check lint
      shell: bash
      run: ./gradlew :clevertap-core:lint :clevertap-geofence:lint  :clevertap-hms:lint  :clevertap-pushTemplates:lint :clevertap-xps:lint

    - name: Upload Lint results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: lint_results
        path:  |
          clevertap-core/build/reports/lint-results.html
          clevertap-hms/build/reports/lint-results.html
          clevertap-xps/build/reports/lint-results.html
          clevertap-geofence/build/reports/lint-results.html
          clevertap-pushTemplates/build/reports/lint-results.html

    - name: Set Output
      if: always()
      uses: actions/github-script@v3 #todo pass fail cancelled ke alag alag status
      shell: bash
      run: |
        echo "slack_msg=Check lint : 🔜" >> $GITHUB_ENV

