# https://github.com/WorkshopOrgTest/PartsTest/blob/17459b939bc7d4dedf3e02164a02a1d668314cb7/.github/workflows/prtest.yml
# check for other workflows https://github.com/sanjaybaskaran01/Valorina/pull/1
# https://github.com/mk8s/mirror-workflow/blob/master/.github/workflows/mirror.yml
# https://github.com/navikt/fp-abakus/blob/master/.github/workflows/promote.yml
# https://github.com/WorkshopOrgTest/prtestcompositeaction/blob/main/action.yml
# https://github.com/navikt/fp-formidling/blob/master/.github/workflows/promote.yml
# https://github.com/web3actions/booster/blob/main/.github/workflows/withdraw.yml
name: PRTEST

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    # main <-- dev-a
    # if: ${{ github.head_ref == 'dev-1' && github.base_ref == 'master' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Comparing Branches
        id: compare
        if: ${{ github.head_ref == 'feature' && github.base_ref == 'development' }}
        run: echo ::set-output name=status::success
        continue-on-error: true

      - name: Get Pull Request ID
        run: |
          export PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "pr_num=$PR_NUMBER" >> $GITHUB_ENV


      - name: Add Comment to Pull Request if Success
        if: steps.compare.outputs.status == 'success'
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ env.pr_num }},
            body: 'Its Success'
            });

      - name: Add Comment to Pull Request if Failure
        if: steps.compare.outputs.status != 'success'
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.createComment({
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: ${{ env.pr_num }},
            body: 'Incorrect PR is created'
            });

      - name: Close PR and Failing action
        if: steps.compare.outputs.status != 'success'
        uses: actions/github-script@v5
        with:
          script: |
            await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo ,
                issue_number: ${{ env.pr_num }},
                state: closed
              });

