#note : this is the most up to date action
name: validate PR raised from task/** branched to develop branch
on:
  pull_request:
    branches: [ develop ]

jobs:
  validate_pr:

    if: startsWith(github.head_ref, 'task/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/workflows/independent/check_mandatory_files_changes.yml
      - uses: ./.github/workflows/independent/lint_codechecks_test_build.yml


#
#      - name: validate commit format -- Check if HEAD commit message contains [xyz] or FAIL
#        uses: gsactions/commit-message-checker@v1
#        with:
#          excludeDescription: 'true'                # optional: this excludes the description body of a pull request
#          excludeTitle: 'true'                      # optional: this excludes the title of a pull request
#          pattern: '^\[[^]]+\].+'                   # this pattern will take all commits as input and check weather the head commit have one  [..] block
#          error: 'Your head commit must contain `[..]` like "[BUGFIX] or [SDK-974]".'
#          checkAllCommitMessages: 'true' # optional: this checks all commits associated with a pull request
#          accessToken: ${{ secrets.GITHUB_TOKEN }} # github access token is only required if checkAllCommitMessages is true
#          #pattern: '^[^#].{74}'     error: 'The maximum line length of 74 characters is exceeded.'
#          #pattern: '^.+(Resolves|Fixes): \#[0-9]+$' #  Check for Resolves / Fixes
#          #flags: 'gm' # more discussion here : https://github.com/GsActions/commit-message-checker/discussions/61,
#
